architecture: amd64

actions:
  - action: debootstrap
    suite: trixie
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    mirror: https://deb.debian.org/debian
    variant: minbase

  - action: apt
    recommends: true
    packages:
      - sudo
      - adduser
      - systemd-sysv
      - firmware-linux

  - action: apt
    recommends: true
    packages:
      - linux-image-amd64

  - action: apt
    packages:
      - systemd-boot
      - grub-efi
      - initramfs-tools
      - ostree

  - action: run
    chroot: true
    command: echo debian > /etc/hostname

  - action: run
    chroot: true
    command: echo 127.0.1.1	debian > /etc/hosts

  - action: "pack"
    compression: gz
    file: build/base-amd64.tar.gz
